use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'QGGScrollSegmentControl_Example' do
  pod 'QGGScrollSegmentControl', :path => '../'
  
  target 'QGGScrollSegmentControl_Tests' do
    inherit! :search_paths

    
  end
end
